"""
Build the site's generated pages from the repository's own sources.

THE ONE RULE. The review deck was hand-written, so it drifted until it
contradicted the repository in five places on the day two hardening items
closed. This site is the opposite: nothing here is a second copy of anything.
The manuscript is split from paper/manuscript.md, the figures are regenerated
from results/, and every number on the home page is read from a results/*.json
at build time. If a number is not in a tracked artifact it does not appear —
which is Rules.md §7 applied to a website.

    python3 site_src/build.py      # writes site_src/docs/** (generated parts)
    mkdocs build                   # renders site/
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "site_src", "docs")
GEN_MARK = "<!-- generated by site_src/build.py — do not edit; edit the source it names -->\n"

DISCLAIMER = """!!! warning "Work in progress — this is not the submitted paper"
    This manuscript is a **living draft**, rendered from `paper/manuscript.md`
    at every push. It has not been peer-reviewed, the venue is undecided, and
    sections may change without notice. Every number in it traces to a committed
    artifact under `results/`, but the text is not final. Cite the repository,
    not this page.

"""


def _load(rel):
    with open(os.path.join(REPO, rel)) as fh:
        return json.load(fh)


# ── figures ──────────────────────────────────────────────────────────────
def figures():
    """Regenerate from results/ when the toolchain is present, then copy."""
    # Opt-in: matplotlib re-stamps the PDFs on every run and dirties the tree.
    # The committed figures ARE generated from results/ — make_figures.py is
    # the only thing that writes them — so copying them keeps the guarantee.
    if os.environ.get("SITE_REGEN_FIGURES"):
        subprocess.run(["python3", "paper/make_figures.py"], cwd=REPO,
                       check=True, capture_output=True, timeout=300)
        print("[site] figures regenerated from results/")
    dst = os.path.join(DOCS, "assets", "figures")
    os.makedirs(dst, exist_ok=True)
    for name in os.listdir(os.path.join(REPO, "paper", "figures")):
        if name.endswith((".png", ".pdf")):
            shutil.copy(os.path.join(REPO, "paper", "figures", name), dst)
    shutil.copy(os.path.join(REPO, "AdaptiShield_Architecture_v3.drawio.png"),
                os.path.join(dst, "implementation_architecture.png"))


# ── manuscript ───────────────────────────────────────────────────────────
def _slug(heading):
    s = re.sub(r"[^a-z0-9]+", "-", heading.lower()).strip("-")
    return s[:60]


def manuscript():
    """paper/manuscript.md as ONE page — a paper scrolls; it does not paginate.

    Sections become anchors, the right-hand table of contents gives navigation,
    and a contents list at the top jumps within the page. The disclaimer appears
    once, at the top, where a reader arriving from anywhere will pass it.
    """
    src = open(os.path.join(REPO, "paper", "manuscript.md")).read()
    src = src.replace("](figures/", "](../assets/figures/")
    src = src.replace("](../AdaptiShield_Architecture_v3.drawio.png)",
                      "](../assets/figures/implementation_architecture.png)")

    parts = re.split(r"^(## .+)$", src, flags=re.M)
    front, sections = parts[0], list(zip(parts[1::2], parts[2::2]))

    # Title block: the H1 and the author lines, centred like a paper's.
    lines = front.strip().split("\n")
    title = lines[0].lstrip("# ").strip()
    rest = "\n".join(lines[1:]).strip()
    abstract_at = rest.find("**Abstract**")
    byline, abstract = (rest[:abstract_at].strip(), rest[abstract_at:].strip()) \
        if abstract_at >= 0 else (rest, "")

    contents = "\n".join(
        f"- [{h[3:].strip()}](#{_slug(h[3:].strip())})" for h, _ in sections)

    body = "".join(
        f'\n\n<a id="{_slug(h[3:].strip())}"></a>\n\n{h}{b}' for h, b in sections)

    page = f"""{GEN_MARK}---
title: Manuscript
hide: [navigation]
---

{DISCLAIMER}
<div class="paper-title" markdown>

# {title}

{byline}

</div>

{abstract}

<div class="paper-contents" markdown>

**Contents**

{contents}

</div>

[:material-file-word: Download the Word draft](https://github.com/ahmadkhanraj01/adaptishield/raw/main/paper/AdaptiShield-Manuscript.docx){{ .md-button }}
[:material-github: Source markdown](https://github.com/ahmadkhanraj01/adaptishield/blob/main/paper/manuscript.md){{ .md-button }}

---
{body}

<style>
.paper-title{{text-align:center;margin:1rem 0 1.5rem}}
.paper-title h1{{margin-bottom:.6rem}}
.paper-contents{{columns:2;column-gap:2rem;font-size:.85rem;margin:1rem 0}}
.paper-contents ul{{margin:0}}
@media (max-width:700px){{.paper-contents{{columns:1}}}}
.md-typeset h2{{margin-top:2.6rem}}
</style>
"""
    out = os.path.join(DOCS, "manuscript")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    with open(os.path.join(out, "index.md"), "w") as fh:
        fh.write(page)
    print(f"[site] manuscript: one page, {len(sections)} sections")
    return [("Manuscript", "manuscript/index.md")]


# ── numbers, from results/ only ──────────────────────────────────────────
def numbers():
    camp = _load("results/campaign/campaign.json")["summary"]
    nf = _load("results/noise_floor/agentdojo_benign.json")["summary"]
    tr = _load("results/phase16_model_transfer/transfer.json")
    inc, cand = tr["models"]["incumbent"], tr["models"]["candidate"]

    def pct(x): return f"{100*x:.1f}%"
    def ci(r): return f"[{100*r['ci_low']:.1f}%, {100*r['ci_high']:.1f}%]"

    det, ext = camp["detection"], camp["benign"]["fpr_external"]
    t_inc, t_cand = tr["per_model"][inc], tr["per_model"][cand]
    return {
        "detection": (f"{det['hits']}/{det['n']} = {pct(det['rate'])}", ci(det), "results/campaign/"),
        "fpr": (f"{ext['hits']}/{ext['n']} = {pct(ext['rate'])}", ci(ext) + f" · stable over {nf['n_runs']} recordings", "results/noise_floor/"),
        # ⚠ transfer.json is ONE recording per model — its own `repeats` field says
        # so, and says no run-to-run spread may be quoted from it. The label has to
        # carry that: the paper's headline for the incumbent's no-target stratum is
        # 10.0%, the median of three recordings in results/noise_floor/, and a tile
        # reading 13.3% without "run 0" on it looks like the paper contradicting
        # the site.
        "strat_inc": (f"{pct(t_inc['IA-target']['rate'])} vs {pct(t_inc['IA-notarget']['rate'])}", f"{inc} · run 0 · gap {100*tr['gap'][inc]:.1f} pts", "results/phase16_model_transfer/"),
        "strat_cand": (f"{pct(t_cand['IA-target']['rate'])} vs {pct(t_cand['IA-notarget']['rate'])}", f"{cand} · run 0 · gap {100*tr['gap'][cand]:.1f} pts", "results/phase16_model_transfer/"),
        "misses": (", ".join(camp["misses"]), "every one address-free", "results/campaign/"),
    }


def external():
    """Published attack-success figures we position against — verbatim rows only.

    Two gates, both deliberate. `verified` must be "verbatim", so a row that no
    human has read out of its primary source cannot reach the site any more than
    it can reach the manuscript. And only the attack-success family is shown:
    PIShield's table is FPR/FNR, a different axis, and mixing the two under one
    "Reported" column would put a detector's false-positive rate beside a
    defence's ASR as though they were comparable.
    """
    with open(os.path.join(REPO, "paper", "external_numbers.json")) as fh:
        data = json.load(fh)
    out = []
    for src in data["sources"]:
        for row in src["rows"]:
            metric = row.get("metric", "")
            if row.get("verified") != "verbatim":
                continue
            if "attack success" not in metric and "ASR" not in metric:
                continue
            value = row.get("display") or f"{row['value_pct']}%"
            out.append((row["system"], row.get("setting", "—"), metric, value,
                        src["citation"].split(",")[0], src["url"]))
    return out


def home():
    n = numbers()
    head = _git("rev-parse", "--short", "HEAD")
    ext = "\n".join(
        ["| Published system | Setting | Metric | Rate |", "| :--- | :--- | :--- | ---: |"]
        + [f"| {sys_} [{who}]({url}) | {setting} | {metric} | **{value}** |"
           for sys_, setting, metric, value, who, url in external()])
    tiles = "\n".join(
        f'<div class="tile"><div class="big">{v[0]}</div><div class="lbl">{k}</div>'
        f'<div class="sub">{v[1]}</div><div class="src"><code>{v[2]}</code></div></div>'
        for k, v in {
            "Detection, our campaign": n["detection"],
            "False positives, external benign (n=60)": n["fpr"],
            "InjecAgent by stratum — incumbent": n["strat_inc"],
            "InjecAgent by stratum — second model": n["strat_cand"],
        }.items())
    page = f"""{GEN_MARK}# AdaptiShield

**Causal prompt-injection detection depends on a liftable target.** A six-layer
defence for tool-integrated LLM agents, evaluated against externally-authored
attacks, a published baseline, and component by component — and reported
honestly where it stops working.

!!! quote "The one claim everything reduces to"
    The causal contrast carries discriminative signal when the injected content
    names a **liftable target** — an address or URL an action can name — and
    close to none otherwise.

!!! success "Research phase closed — 15 September 2026"
    Every measurement phase is done and the manuscript is drafted against
    committed artifacts. The paper is now being written in the authors' own
    words from the [Write-up](writeup/README.md) digests. What remains is
    administrative: venue, author block, two human reads. See [Progress](progress.md).

## Numbers of record

<div class="tiles">
{tiles}
</div>

*Every tile is read from a `results/*.json` at build time — commit `{head}`,
built {time.strftime("%Y-%m-%d %H:%M %z")}. Nothing on this page is typed by hand.*

The four misses on our own corpus: `{n["misses"][0]}` — {n["misses"][1]}.

!!! info "Why the InjecAgent tiles say *run 0*"
    Those two tiles come from `results/phase16_model_transfer/`, which is **one
    recording per model** — the artifact's own manifest says no run-to-run spread
    may be quoted from it. The manuscript's headline for the incumbent's no-target
    stratum is **10.0%**, the *median of three* recordings in
    `results/noise_floor/`. Both are correct for their own artifact; they are not
    the same measurement, and the paired comparison between the two models is only
    valid run-0-against-run-0.

## Against published results

{ext}

*Attack-success figures only, read from `paper/external_numbers.json`, which
admits a row only once a human has read it in the primary source. The detector
landscape is a different axis and lives in §XI. None of these is a like-for-like
comparison with ours, and the manuscript says why for each — the pair worth
reading together is AgentDojo's own **57.69% undefended → 41.65% delimited**,
the only published prompt-level result here carrying its own baseline.*

## Where to go

| | |
| :--- | :--- |
| [The manuscript](manuscript/index.md) | the paper as a living draft, one page per section |
| [Architecture](architecture.md) | the six layers and the causal sub-layer |
| [Write-up](writeup/README.md) | the bullet-point digests the paper is written from, with every number sourced |
| [Progress](progress.md) | phase roadmap and what is open |

<style>
.tiles{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem;margin:1rem 0}}
.tile{{border:1px solid var(--md-default-fg-color--lightest);border-radius:8px;padding:1rem}}
.tile .big{{font-size:1.5rem;font-weight:700;line-height:1.2}}
.tile .lbl{{font-weight:600;margin-top:.3rem}}
.tile .sub,.tile .src{{font-size:.8rem;opacity:.75;margin-top:.2rem}}
</style>
"""
    with open(os.path.join(DOCS, "index.md"), "w") as fh:
        fh.write(page)
    print("[site] home page generated")


def _git(*args):
    return subprocess.run(("git",) + args, cwd=REPO, capture_output=True,
                          text=True).stdout.strip()


GITHUB = "https://github.com/ahmadkhanraj01/adaptishield/blob/main/"


def _repo_links(md):
    """Relative links to repo files (README.md, Rules.md, evaluation/...) become
    GitHub links — those files are deliberately not part of the site."""
    return re.sub(r"\]\(((?!https?://|#|assets/|manuscript/)[^)]+\.(?:md|py|json|txt|yaml|yml|html))(#[^)]*)?\)",
                  lambda m: f"]({GITHUB}{m.group(1)}{m.group(2) or ''})", md)


# ── architecture & progress (thin wrappers over existing files) ─────────
def architecture():
    src = _repo_links(open(os.path.join(REPO, "Architecture.md")).read())
    page = (GEN_MARK + "# Architecture\n\n"
            "![Fig. 0 — the pipeline](assets/figures/fig0_architecture.png)\n\n"
            "*Print schematic from the paper. Components in colour are the two "
            "that move a measured outcome (§V).*\n\n"
            "![Implementation architecture](assets/figures/implementation_architecture.png)\n\n"
            "---\n\n*The section below is `Architecture.md` from the repository, "
            "rendered as-is.*\n\n" + src)
    with open(os.path.join(DOCS, "architecture.md"), "w") as fh:
        fh.write(page)


# ── write-up (the bullet-point digests the paper is written from) ────────
WRITEUP_PAGES = [  # (source file, nav title) — order is reading order
    ("README.md", "How to use"),
    ("00-abstract.md", "Abstract"),
    ("01-introduction.md", "Introduction"),
    ("02-related-work.md", "Related work"),
    ("03-methodology.md", "Methodology"),
    ("04-experiments-results.md", "Experiments and results"),
    ("05-discussion.md", "Discussion"),
    ("06-conclusion.md", "Conclusion"),
    ("rules/general-research-paper-rules.md", "Rules: research paper"),
    ("rules/journal-paper-rules.md", "Rules: journal paper"),
]

WRITEUP_NOTE = """!!! note "What this section is"
    The paper is being written in the authors' own words from these digests.
    Each bullet carries its number, its `results/` source, and a `[meaning …]`
    bracket in plain words. They are copied from `writeup/` in the repository
    at every push; the figures are the paper's own. This is scaffolding for the
    manuscript, not the manuscript.

"""


def writeup():
    """writeup/**.md copied page-for-page, figure paths pointed at the shared
    assets, internal links kept internal, repo links sent to GitHub."""
    src_dir = os.path.join(REPO, "writeup")
    out = os.path.join(DOCS, "writeup")
    shutil.rmtree(out, ignore_errors=True)
    internal = {rel for rel, _ in WRITEUP_PAGES}
    nav = []
    for rel, title in WRITEUP_PAGES:
        md = open(os.path.join(src_dir, rel)).read()
        depth = rel.count("/")
        up = "../" * (depth + 1)
        md = md.replace("figures/fig5_implementation_diagram.png",
                        "figures/implementation_architecture.png")
        md = re.sub(r"\]\(figures/([^)]+\.png)\)", rf"]({up}assets/figures/\1)", md)

        def link(m):
            target, frag = m.group(1), m.group(2) or ""
            if target in internal:
                # keep relative to this page's own directory
                if depth and not target.startswith("rules/"):
                    return f"]({'../' * depth}{target}{frag})"
                if not depth and target.startswith("rules/"):
                    return f"]({target}{frag})"
                if depth and target.startswith("rules/"):
                    return f"]({target[len('rules/'):]}{frag})"
                return f"]({target}{frag})"
            return f"]({GITHUB}{target}{frag})"
        md = re.sub(r"\]\(((?!https?://|#|\.\./|assets/)[^)]+\.(?:md|py|json|txt|yaml|yml|html))(#[^)]*)?\)",
                    link, md)
        dst = os.path.join(out, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w") as fh:
            fh.write(GEN_MARK + WRITEUP_NOTE + md)
        nav.append(f"    - \"{title}\": writeup/{rel}")
    print(f"[site] write-up: {len(nav)} pages from writeup/")
    return "\n".join(nav)


STATUS = [  # (marker, css class, label) — status is icon + label, never colour alone
    ("⛔", "withdrawn", "withdrawn"),
    ("🔴", "open", "open defect"),
    ("🔲", "next", "planned"),
    ("🟡", "partial", "partial"),
    ("🔵", "blocked", "blocked"),
    ("✅", "done", "done"),
]


def _status(cell):
    for marker, cls, label in STATUS:
        if marker in cell:
            return marker, cls, label
    return "·", "unknown", "unknown"


def _phase_rows(md):
    """Rows of Phase.md's Snapshot table: (id, scope, state-cell)."""
    rows = []
    for line in md.split("\n"):
        m = re.match(r"^\|\s*\**([0-9]+[a-z]?)\**\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$", line)
        if m:
            rows.append(m.groups())
    return rows


def _strip_md(s):
    return re.sub(r"[*_`]|\(§[^)]*\)", "", s).strip()


def progress():
    src = _repo_links(open(os.path.join(REPO, "Phase.md")).read())
    rows = _phase_rows(src)

    # Anchor every "### N · …" section so the board can deep-link into it.
    def anchor(m):
        return f'<a id="phase-{m.group(1).lower()}"></a>\n{m.group(0)}'
    src = re.sub(r"^### ([0-9]+[a-z]?) · .+$", anchor, src, flags=re.M)
    section_ids = set(re.findall(r'id="phase-([0-9a-z]+)"', src))

    counts = {}
    cards = []
    for pid, scope, state in rows:
        marker, cls, label = _status(state)
        counts[label] = counts.get(label, 0) + 1
        short = _strip_md(state)
        short = (short[:90] + "…") if len(short) > 90 else short
        href = f"#phase-{pid.lower()}" if pid.lower() in section_ids else "#snapshot"
        cards.append(
            f'<a class="ph {cls}" href="{href}">'
            f'<span class="id">{pid}</span>'
            f'<span class="st">{marker} {label}</span>'
            f'<span class="sc">{_strip_md(scope)}</span>'
            f'<span class="dt">{short}</span></a>')

    stats = "".join(
        f'<div class="stat"><b>{counts.get(l, 0)}</b><span>{m} {l}</span></div>'
        for m, _, l in STATUS if counts.get(l))

    toc = "\n".join(
        f"- [{_strip_md(h)}](#phase-{i.lower()})"
        for i, h in re.findall(r"^### ([0-9]+[a-z]?) · (.+?)\s+—", src, flags=re.M))

    head = f"""{GEN_MARK}# Progress

*Generated from `Phase.md`'s Snapshot table and section headings at build time.
Status is shown as icon + label: ✅ done · 🟡 partial · 🔲 planned · 🔴 open
defect · 🔵 blocked · ⛔ withdrawn. Click a card to jump to that phase's section.*

<div class="stats">{stats}</div>

## Phase board

<div class="board">
{chr(10).join(cards)}
</div>

## Sections

{toc}

---

*Below is `Phase.md` from the repository, rendered as-is.*

<style>
.stats{{display:flex;gap:.75rem;flex-wrap:wrap;margin:.5rem 0 1rem}}
.stat{{border:1px solid var(--md-default-fg-color--lightest);border-radius:8px;padding:.5rem .9rem;min-width:7rem}}
.stat b{{display:block;font-size:1.4rem;line-height:1.1}}
.stat span{{font-size:.75rem;opacity:.75}}
.board{{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:.6rem;margin:1rem 0}}
.ph{{display:flex;flex-direction:column;gap:.15rem;padding:.6rem .7rem;border-radius:8px;
     border:1px solid var(--md-default-fg-color--lightest);border-left-width:5px;
     color:var(--md-default-fg-color) !important;text-decoration:none !important;font-size:.78rem}}
.ph:hover{{background:var(--md-default-fg-color--lightest)}}
.ph .id{{font-family:var(--md-code-font-family);font-weight:700;font-size:.95rem}}
.ph .st{{font-weight:600}}
.ph .sc{{opacity:.9}}
.ph .dt{{opacity:.6;font-size:.7rem}}
.ph.done{{border-left-color:#2e7d5b}} .ph.partial{{border-left-color:#c98a00}}
.ph.next{{border-left-color:#7a7a7a}} .ph.open{{border-left-color:#c0392b}}
.ph.blocked{{border-left-color:#2f6fb5}} .ph.withdrawn{{border-left-color:#555;opacity:.7}}
</style>

"""
    with open(os.path.join(DOCS, "progress.md"), "w") as fh:
        fh.write(head + src)
    print(f"[site] progress: {len(rows)} phases on the board, {len(section_ids)} deep links")


def write_config(manuscript_nav, writeup_nav):
    """mkdocs.yml is generated too, so the nav tracks the manuscript's sections."""
    cfg = f"""# GENERATED by site_src/build.py — edit the template there, not this file.
site_name: AdaptiShield
site_description: Causal prompt-injection detection depends on a liftable target
site_url: https://ahmadkhanraj01.github.io/adaptishield/
repo_url: https://github.com/ahmadkhanraj01/adaptishield
repo_name: ahmadkhanraj01/adaptishield
docs_dir: site_src/docs
site_dir: site
theme:
  name: material
  features: [navigation.tabs, navigation.sections, navigation.top, search.suggest, content.code.copy, toc.follow]
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle: {{icon: material/brightness-7, name: Dark}}
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle: {{icon: material/brightness-4, name: Light}}
markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc: {{permalink: true}}
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Manuscript: manuscript/index.md
  - Write-up:
{writeup_nav}
  - Progress: progress.md
"""
    with open(os.path.join(REPO, "mkdocs.yml"), "w") as fh:
        fh.write(cfg)


if __name__ == "__main__":
    os.makedirs(DOCS, exist_ok=True)
    figures()
    nav = manuscript()
    home()
    architecture()
    progress()
    wnav = writeup()
    write_config(nav, wnav)
    print("[site] done")
